> setwd("C:/Users/mbuck/Documents/Matt's Files/Personal/School/Data Bootcamp/Repository/R_Analysis")
> mecha_car_mpg <- read.csv("MechaCar_mpg.csv")
> install.packages("dplyr")
> library(dplyr)
> mecha_car_mpg <- read.csv("MechaCar_mpg.csv")
> model <- lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_car_mpg)
> summary(model)
> suspension_coil <- read.csv("Suspension_Coil.csv")
> View(suspension_coil)
> total_summary <- suspension_coil %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
> lot_summary <- suspension_coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean =mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI))
> t.test(suspension_coil$PSI, mu = 1500)
> t.test(subset(suspension_coil, Manufacturing_Lot == "Lot1")$PSI,mu=1500)
> t.test(subset(suspension_coil, Manufacturing_Lot == "Lot2")$PSI, mu=1500)
> t.test(subset(suspension_coil, Manufacturing_Lot == "Lot3")$PSI, mu=1500)
